name = "DeepSeek V3.1 Nex N1"
family = "deepseek"
release_date = "2025-12-10"
last_updated = "2025-12-10"
attachment = false
reasoning = false
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 0.27999999999999997
output = 0.42000000000000004

[limit]
context = 128_000
input = 128_000
output = 8_192

[modalities]
input = ["text"]
output = ["text"]
