base_model = "zhipuai/glm-5.3-flash"
name = "GLM5.3 Flash"

[[reasoning_options]]
type = "effort"
values = ["medium", "high", "xhigh"]

[cost]
input = 0.15
output = 0.5
cache_read = 0.03

[limit]
context = 1_048_576
output = 1_048_576

[modalities]
input = ["text", "image", "video"]
