base_model = "anthropic/claude-sonnet-4-6"
name = "Claude Sonnet 4.6 (EU)"
structured_output = true

[[reasoning_options]]
type = "effort"
values = ["none", "low", "medium", "high", "max"]

[[reasoning_options]]
type = "budget_tokens"

[cost]
input = 3.3
output = 16.5
cache_read = 0.3
cache_write = 4.125
