# Source: https://www.ibm.com/products/watsonx-ai/pricing (accessed 2026-08-08)
# Model details: https://www.ibm.com/docs/en/watsonx/saas?topic=solutions-supported-foundation-models (accessed 2026-08-08)
base_model = "mistral/mistral-small-3-1-24b-instruct-2503"

[cost]
input = 0.106
output = 0.318

[limit]
context = 131_072
