name = "Gemma 4"
release_date = "2026-04-22"
last_updated = "2026-04-22"
attachment = false
reasoning = false
temperature = true
tool_call = false
open_weights = true

[cost]
input = 5.0
output = 10.0

[limit]
context = 32_768
output = 8_192

[modalities]
input = ["text"]
output = ["text"]
