# Toggle: reasoning.enabled = true|false
# https://vercel.com/docs/ai-gateway/sdks-and-apis/openai-chat-completions/reasoning
base_model = "anthropic/claude-opus-4-20250514"

[[reasoning_options]]
type = "toggle"

[[reasoning_options]]
type = "budget_tokens"
min = 1_024

[cost]
input = 15
output = 75
cache_read = 1.5
cache_write = 18.75
