base_model = "alibaba/qwen3-235b-a22b-instruct-2507"
name = "Qwen3 235B A22B Instruct 2507 (Vertex AI (OpenAI-compatible))"
structured_output = false

[cost]
input = 0.22
output = 0.88

[limit]
output = 32_768
