# Not included in subscription
name = "Grok Latest"
release_date = "2026-05-03"
last_updated = "2026-05-03"
attachment = true
reasoning = true
reasoning_options = [{ type = "effort", values = ["low", "medium", "high"] }]
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 1.25
output = 2.5
cache_read = 0.2

[limit]
context = 1000000
input = 1000000
output = 1000000

[modalities]
input = ["text", "image"]
output = ["text"]
