base_model = "moonshotai/kimi-k2.5"
description = "Kimi K2.5 is a multimodal Mixture-of-Experts language model featuring 32 billion activated parameters and a total of 1 trillion parameters."
release_date = "2026-02-02"
last_updated = "2026-02-02"
attachment = true
temperature = true
reasoning_options = []

[cost]
input = 0.6
output = 3
cache_read = 0.1

[modalities]
input = ["text", "image"]
