base_model = "zhipuai/glm-4.7-flash"
reasoning_options = []

[cost]
input = 0.04
output = 0.3
cache_read = 0.008
cache_write = 0

[limit]
context = 202_752

[provider]
npm = "@ai-sdk/openai-compatible"
