name = "ReMM SLERP 13B"
family = "llama"
release_date = "2025-01-01"
last_updated = "2025-01-01"
attachment = true
reasoning = false
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 0.7989999999999999
output = 1.2069999999999999

[limit]
context = 6_144
input = 6_144
output = 4_096

[modalities]
input = ["text", "pdf"]
output = ["text"]
