base_model = "swiss-ai/apertus-70b"
description = "Apertus 70B is an open, multilingual language model designed for research, long-context reasoning, and sovereignty-focused AI systems."
reasoning = true
temperature = false
structured_output = false
reasoning_options = []

[cost]
input = 1.393
output = 2.228

[limit]
output = 65_536
