base_model = "mistral/voxtral-small-24b-2507"
name = "Voxtral Small 24B 2507 (Amazon Bedrock, US)"
tool_call = false
structured_output = false

[cost]
input = 0.1
output = 0.3

[limit]
context = 128_000
