base_model = "nvidia/nemotron-nano-9b-v2"
name = "Nemotron Nano 9B v2 (US)"
tool_call = false
structured_output = false
reasoning_options = []

[cost]
input = 0.06
output = 0.23

[limit]
context = 128_000
