name = "Grok 4.20 Beta Reasoning"
family = "grok"
attachment = true
reasoning = true
tool_call = true
temperature = true
release_date = "2026-03-11"
last_updated = "2026-03-13"
open_weights = false

[cost]
input = 2
output = 6
cache_read = 0.19999999999999998

[limit]
context = 2_000_000
output = 2_000_000

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
