name = "Nous: Hermes 4 405B"
description = "Reasoning model for deliberate analysis, multi-step problem solving, and tool use"
family = "nousresearch"
release_date = "2025-08-26"
last_updated = "2025-08-26"
attachment = false
reasoning = true
temperature = true
tool_call = false
structured_output = false
open_weights = false

[[reasoning_options]]
type = "effort"
values = ["none", "high"]

[cost]
input = 1
output = 3

[limit]
context = 131_072
output = 26_215

[modalities]
input = ["text"]
output = ["text"]
