name = "OpenAI o3-mini (High)"
description = "O-series reasoning model for hard analysis, math, coding, and planning"
family = "o-mini"
release_date = "2025-01-31"
last_updated = "2025-01-31"
attachment = false
reasoning = true
reasoning_options = []
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.64
output = 2.588

[limit]
context = 200_000
input = 200_000
output = 100_000

[modalities]
input = ["text"]
output = ["text"]
