base_model = "openai/o4-mini-deep-research"
name = "OpenAI o4-mini Deep Research"
attachment = false
tool_call = false
structured_output = false

[[reasoning_options]]
type = "effort"
values = ["medium"]

[cost]
input = 2.2
output = 8.8
cache_read = 1.1

[limit]
input = 200_000

[modalities]
input = ["text"]
