name = "GPT-5.4"
family = "gpt"
attachment = true
reasoning = true
tool_call = true
structured_output = true
temperature = true
release_date = "2026-03-05"
last_updated = "2026-03-09"
open_weights = false

[cost]
input = 3.13
output = 18.8
cache_read = 0.313

[limit]
context = 1_000_000
output = 131_072

[modalities]
input = ["text", "image"]
output = ["text"]
