name = "MiniMax M2.1"
family = "minimax"
attachment = false
reasoning = true
tool_call = true
structured_output = true
temperature = true
release_date = "2025-12-01"
last_updated = "2026-03-16"
open_weights = true

[interleaved]
field = "reasoning_content"

[cost]
input = 0.35
output = 1.5
cache_read = 0.04

[limit]
context = 198_000
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
