base_model = "openai/gpt-4o-mini"
name = "GPT-4o Mini"
family = "gpt"
release_date = "2026-02-28"
last_updated = "2026-06-11"

[cost]
input = 0.1875
output = 0.75
cache_read = 0.09375

[modalities]
input = ["text", "image"]
