name = "Poolside: Laguna M.1 (free)"
release_date = "2026-04-28"
last_updated = "2026-06-13"
attachment = false
reasoning_options = []
reasoning = true
tool_call = true
temperature = true
open_weights = false

[cost]
input = 0.0
output = 0.0

[limit]
context = 262144
output = 32768

[modalities]
input = ["text"]
output = ["text"]
