name = "Magistral Small 1.2 24B"
family = "magistral-small"
release_date = "2025-06-01"
last_updated = "2025-06-01"
attachment = false
reasoning = false
tool_call = false
open_weights = true

[cost]
input = 0.59
output = 2.36

[limit]
context = 131_072
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
