name = "Aion 1.0"
family = "llama"
release_date = "2025-02-01"
last_updated = "2025-02-01"
attachment = false
reasoning = false
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 3.995
output = 7.99

[limit]
context = 65_536
input = 65_536
output = 8_192

[modalities]
input = ["text"]
output = ["text"]
