base_model = "xiaomi/mimo-v2.5"
reasoning_options = [{ type = "toggle" }]
name = "MiMo M2.5"
family = "mimo-v2.5"
open_weights = false

[cost]
input = 0.14
output = 0.28
cache_read = 0.0028

[limit]
context = 1_050_000
output = 131_100

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
