name = "Whisper Large v3"
family = "whisper"
release_date = "2023-09-01"
last_updated = "2026-03-17"
attachment = false
reasoning = false
temperature = false
knowledge = "2023-09"
tool_call = false
open_weights = true

[cost]
input = 0.003
output = 0.0

[limit]
context = 0
output = 8_192

[modalities]
input = ["audio"]
output = ["text"]