name = "klokintegration.se"
npm = "@ai-sdk/openai-compatible"
env = ["KLOKINTEGRATION_API_KEY"]
api = "https://api-gw.klok.ipaas.se/proxy/kloker-key/v1"
doc = "https://klokintegration.se/docs/ai-api"
