name = "Claude 3.7 Sonnet Thinking (32K)"
release_date = "2025-07-15"
last_updated = "2025-07-15"
attachment = true
reasoning = true
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 2.992
output = 14.994

[limit]
context = 200_000
input = 200_000
output = 64_000

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
