name = "Doubao 1.5 Pro 32k"
release_date = "2025-01-22"
last_updated = "2025-01-22"
attachment = false
reasoning = false
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 0.1343
output = 0.3349

[limit]
context = 32_000
input = 32_000
output = 8_192

[modalities]
input = ["text"]
output = ["text"]
