name = "Exa (Research Pro)"
release_date = "2025-06-04"
last_updated = "2025-06-04"
attachment = false
reasoning = false
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 2.5
output = 2.5

[limit]
context = 16_384
input = 16_384
output = 16_384

[modalities]
input = ["text"]
output = ["text"]
