base_model = "zhipuai/glm-5-turbo"

[[reasoning_options]]
type = "toggle"

[cost]
input = 0.9
output = 3.7
cache_read = 0.18
cache_write = 0.9

[[cost.tiers]]
tier = { type = "context", size = 32_000 }
input = 1.1
output = 4.3
cache_read = 0.27
cache_write = 1.1

[limit]
output = 128_000
