# Not included in subscription
name = "Solar Pro 3"
release_date = "2026-03-03"
last_updated = "2026-03-03"
attachment = false
reasoning = false
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 0.15
output = 0.6
cache_read = 0.015

[limit]
context = 128000
input = 128000
output = 128000

[modalities]
input = ["text"]
output = ["text"]
