name = "Kling v3.0 Motion Control"
family = "ling"
release_date = "2026-03-04"
last_updated = "2026-03-04"
attachment = false
reasoning = false
temperature = true
tool_call = false
open_weights = false

[limit]
context = 0
output = 0

[modalities]
input = ["text"]
output = ["video"]
