base_model = "minimax/MiniMax-M2-Her"
name = "MiniMax M2-her"
reasoning = false
tool_call = false
structured_output = false

[cost]
input = 0.302
output = 1.207
cache_read = 0.151

[limit]
context = 65_532
input = 65_532
