name = "Claudius"
release_date = "2026-05-12"
last_updated = "2026-05-12"
attachment = true
reasoning = true
tool_call = true
open_weights = false
knowledge = "2026-05"

[cost]
input = 3.00
output = 8.00
cache_read = 0.900

[limit]
context = 256_000
output = 64_000

[modalities]
input = ["text", "image", "audio", "video"]
output = ["text"]
