# Source: https://api-gateway.merge.dev/v1/models?model=cohere%2Fcommand-r-plus-08-2024 (accessed 2026-07-21)

base_model = "cohere/command-r-plus-08-2024"
name = "Command R+ 08-2024"
structured_output = true

[cost]
input = 2.5
output = 10
