base_model = "deepseek/deepseek-r1"
name = "Deepseek R1 Distill Qwen 32B"
reasoning_options = []
tool_call = false
structured_output = false

[cost]
input = 0.497
output = 4.881

[limit]
context = 80_000
output = 80_000
