name = "Dolphin 72b"
family = "qwen"
release_date = "2025-02-27"
last_updated = "2025-02-27"
attachment = false
reasoning = false
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 0.306
output = 0.306

[limit]
context = 8_192
input = 8_192
output = 4_096

[modalities]
input = ["text"]
output = ["text"]
