name = "Llama 3.2 3b Instruct"
family = "llama"
release_date = "2024-09-25"
last_updated = "2024-09-25"
attachment = true
reasoning = false
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 0.0306
output = 0.0493

[limit]
context = 131_072
input = 131_072
output = 8_192

[modalities]
input = ["text", "pdf"]
output = ["text"]
