name = "Alibaba Coding Plan (China)"
env = ["ALIBABA_CODING_PLAN_API_KEY"]
npm = "@ai-sdk/openai-compatible"
doc = "https://help.aliyun.com/zh/model-studio/coding-plan"
api = "https://coding.dashscope.aliyuncs.com/v1"
