name = "Mistral: Ministral 3 8B 2512"
release_date = "2025-12-02"
last_updated = "2026-03-15"
attachment = true
reasoning = false
temperature = true
tool_call = true
open_weights = true

[cost]
input = 0.15
output = 0.15

[limit]
context = 262144
output = 32768

[modalities]
input = ["image", "text"]
output = ["text"]
