name = "Qwen 3 Max Thinking"
family = "qwen"
release_date = "2026-01-23"
last_updated = "2025-01"
attachment = false
reasoning = true
temperature = true
tool_call = true
knowledge = "2025-01"
open_weights = true

[cost]
input = 1.2
output = 6
cache_read = 0.24

[limit]
context = 256_000
output = 65_536

[modalities]
input = ["text"]
output = ["text"]
