name = "Qwen3 Coder 480B A35B Instruct"
family = "qwen"
release_date = "2025-07-22"
last_updated = "2025-04"
attachment = false
reasoning = true
temperature = true
tool_call = true
knowledge = "2025-04"
open_weights = false
reasoning_options = []

[cost]
input = 1.5
output = 7.5
cache_read = 0.3

[limit]
context = 262_144
output = 65_536

[modalities]
input = ["text"]
output = ["text"]
