base_model = "bytedance-seed/seed-2.0-mini"
reasoning_options = []

[cost]
input = 0.1
output = 0.4
cache_read = 0.02

[[cost.tiers]]
tier = { type = "context", size = 128_000 }
input = 0.2
output = 0.8
cache_read = 0.2

[modalities]
input = ["text", "image"]
