# Included in subscription
name = "Qwen3 Coder Next"
release_date = "2025-12-08"
last_updated = "2025-12-08"
attachment = false
reasoning = false
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.15
output = 1.5

[limit]
context = 262144
input = 262144
output = 65536

[modalities]
input = ["text"]
output = ["text"]
