# Included in subscription
name = "Qwen3 Next 80B A3B (Instruct)"
release_date = "2025-09-11"
last_updated = "2025-09-11"
attachment = false
reasoning = false
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.15
output = 0.65

[limit]
context = 256000
input = 256000
output = 262144

[modalities]
input = ["text"]
output = ["text"]
