# Included in subscription
name = "Qwen3 30B A3B"
release_date = "2025-02-27"
last_updated = "2025-02-27"
attachment = false
reasoning = false
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 0.1
output = 0.3

[limit]
context = 41000
input = 41000
output = 32768

[modalities]
input = ["text"]
output = ["text"]
