name = "Amazon Nova Lite 1.0"
family = "nova-lite"
release_date = "2024-12-03"
last_updated = "2024-12-03"
attachment = false
reasoning = false
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 0.0595
output = 0.238

[limit]
context = 300_000
input = 300_000
output = 5_120

[modalities]
input = ["text"]
output = ["text"]
