# Included in subscription (uses 2x input tokens)
base_model = "deepseek/deepseek-v4-pro"

[[reasoning_options]]
type = "effort"
values = ["none", "high", "max"]

[cost]
input = 1.1
output = 2.2
cache_read = 0.11

[limit]
context = 1_048_576
input = 1_048_576
