# Source: https://routellm.abacus.ai/v1/models
# RouteLLM input_modalities: ['text', 'image']
# RouteLLM output_modalities: ['text']
# RouteLLM context_length: 200000
# RouteLLM max_completion_tokens: 64000
# RouteLLM input_token_rate: 0.000005
# RouteLLM output_token_rate: 0.000025
# RouteLLM thinking: True
base_model = "anthropic/claude-opus-4-5-20251101"
reasoning = true
reasoning_options = []

[cost]
input = 5.00
output = 25.00

[limit]
context = 200_000
output = 64_000

[modalities]
input = ["text", "image"]
output = ["text"]
