name = "GPT-Realtime-1.5"
family = "gpt"
release_date = "2026-02-23"
last_updated = "2026-02-23"
attachment = false
reasoning = false
temperature = true
tool_call = false
open_weights = false

[cost]
input = 4
output = 16
cache_read = 0.4

[limit]
context = 0
output = 0

[modalities]
input = ["text", "audio"]
output = ["text", "audio"]
