base_model = "minimax/MiniMax-M2.5"
name = "MiniMax-M2.5"
release_date = "2026-02-12"
last_updated = "2026-02-12"
structured_output = true
reasoning_options = []

[interleaved]
field = "reasoning_content"

[cost]
input = 0.3
output = 1.2
cache_read = 0.06

[limit]
context = 196_608
output = 196_608
