base_model = "alibaba/qwen3.6-35b-a3b"
reasoning_options = [{ type = "toggle" }]
name = "Qwen 3.6 35B A3B FP8"

[cost]
input = 0.17
output = 1.1
cache_read = 0.056

[limit]
output = 32_768

[modalities]
input = ["text"]
