name = "Qwen3 Max (2026-01-23)"
family = "qwen"
release_date = "2026-01-23"
last_updated = "2026-01-23"
attachment = true
reasoning = true
temperature = true
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 1.2
output = 6
cache_read = 0.24
cache_write = 1.5

[limit]
context = 262_144
output = 32_800

[modalities]
input = ["text", "image"]
output = ["text"]
