base_model = "minimax/MiniMax-M2.5"
name = "MiniMax M2.5"
description = "MoE model with a highly sparse architecture designed for high-throughput and low latency with strong coding capabilities."
family = "minimax-m2.5"
structured_output = true
reasoning_options = []

[cost]
input = 0.3
output = 1.2
cache_read = 0.3

[limit]
context = 196_608
output = 196_608
