name = "DeepSeek-V3.2"
family = "deepseek"
attachment = false
reasoning = true
reasoning_options = [{ type = "toggle" }]
tool_call = true
structured_output = true
temperature = true
release_date = "2025-12-01"
last_updated = "2025-12-01"
open_weights = true

[interleaved]
field = "reasoning_content"

[cost]
input = 0.5
output = 1.5
cache_read = 0.25

[limit]
context = 163_840
output = 163_840

[modalities]
input = ["text"]
output = ["text"]
