base_model = "openai/o3-deep-research"
temperature = true
structured_output = true
reasoning_options = []

[cost]
input = 10
output = 40
cache_read = 2.5

[modalities]
input = ["image", "text", "pdf"]
