base_model = "minimax/MiniMax-M2"
structured_output = true
reasoning_options = []

[interleaved]
field = "reasoning_details"

[cost]
input = 0.255
output = 1.02

[limit]
context = 204_800
output = 131_072
