base_model = "anthropic/claude-sonnet-4-0"
name = "Claude 4 Sonnet Thinking (32K)"
structured_output = true
reasoning_options = []

[cost]
input = 3
output = 15
cache_read = 0.3

[limit]
context = 1_000_000
input = 1_000_000
