name = "Gemini 2.5 Flash"
release_date = "2025-06-05"
last_updated = "2025-06-05"
attachment = true
reasoning = true
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 0.3
output = 2.5

[limit]
context = 1_048_756
input = 1_048_756
output = 65_536

[modalities]
input = ["text", "image"]
output = ["text"]
