name = "GLM 4.5 Air Derestricted"
release_date = "2025-07-28"
last_updated = "2025-07-28"
attachment = false
reasoning = false
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 0.306
output = 0.306

[limit]
context = 202_600
input = 202_600
output = 98_304

[modalities]
input = ["text"]
output = ["text"]
