name = "Grok 3 Mini Fast Beta"
release_date = "2025-02-17"
last_updated = "2025-02-17"
attachment = false
reasoning = false
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 0.6
output = 4.00

[limit]
context = 131_072
input = 131_072
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
