base_model = "meituan/longcat-2.5-preview"
name = "LongCat 2.5 Preview"
structured_output = false
reasoning_options = []

[cost]
input = 0.75
output = 2.95
cache_read = 0.015

[limit]
input = 1_000_000
