name = "Perplexity Simple"
release_date = "2025-02-19"
last_updated = "2025-02-19"
attachment = false
reasoning = false
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 1.003
output = 1.003

[limit]
context = 127_000
input = 127_000
output = 128_000

[modalities]
input = ["text"]
output = ["text"]
