name = "v0 1.5 LG"
release_date = "2025-07-04"
last_updated = "2025-07-04"
attachment = false
reasoning = false
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 15.00
output = 75.00

[limit]
context = 1_000_000
input = 1_000_000
output = 64_000

[modalities]
input = ["text"]
output = ["text"]
