# Not included in subscription
name = "Claude 4.7 Opus Thinking"
release_date = "2026-04-16"
last_updated = "2026-04-16"
attachment = true
reasoning = true
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 4.998
output = 25.007
cache_read = 0.4998

[limit]
context = 1000000
input = 1000000
output = 128000

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
