name = "DeepSeek: DeepSeek V4 Flash (free)"
release_date = "2026-04-24"
last_updated = "2026-05-16"
attachment = false
reasoning = true
tool_call = true
temperature = false
open_weights = false

[cost]
input = 0
output = 0

[limit]
context = 1048576
output = 384000

[modalities]
input = ["text"]
output = ["text"]
