name = "DeepSeek OCR"
family = "deepseek"
release_date = "2025-10-20"
last_updated = "2026-02-25"
attachment = true
reasoning = false
temperature = true
tool_call = false
open_weights = true

[cost]
input = 0.20
output = 0.70

[limit]
context = 8_192
output = 8_192

[modalities]
input = ["text", "image"]
output = ["text"]
