# Not included in subscription
name = "Gemma 4 31B IT TEE"
release_date = "2026-05-26"
last_updated = "2026-05-26"
attachment = false
reasoning = true
tool_call = true
structured_output = false
open_weights = false

[cost]
input = 0.15
output = 0.46

[limit]
context = 262144
input = 262144
output = 262144

[modalities]
input = ["text"]
output = ["text"]
